#
# Superfaktura project AppVeyor build configuration
#

version: '0.1.0.{build}'

branches:
  only:
    - master
    - release
    - dev
    - /^(.*\/)?ci-.*$/

os: Visual Studio 2015

configuration:
  - Release
  - Debug

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: "0.1.0.{build}"
  assembly_file_version: "0.1.0.{build}"
  assembly_informational_version: "{version} ({branch})"

environment:
  - CLI_VERSION: 1.0.0-preview2-003121

init:
  - git config --global core.autocrlf true

install:
  - ps: $url = "https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/$($env:CLI_VERSION)/dotnet-dev-win-x64.$($env:CLI_VERSION.ToLower()).zip"
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"
  - ps: mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null
  - ps: $tempFile = [System.IO.Path]::GetTempFileName()
  - ps: (New-Object System.Net.WebClient).DownloadFile($url, $tempFile)
  - ps: Add-Type -AssemblyName System.IO.Compression.FileSystem; [System.IO.Compression.ZipFile]::ExtractToDirectory($tempFile, $env:DOTNET_INSTALL_DIR)
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"

before_build:
  - ps: dotnet --info
  - cmd: nuget restore Superfaktura.sln

build:
  project: Superfaktura.sln
  verbosity: normal

test: off

cache:
  - packages -> **\packages.config
