#
# Superfaktura project AppVeyor build configuration
#

version: '0.1.0.{build}'

branches:
  only:
    - master
    - release
    - dev
    - /^(.*\/)?ci-.*$/

os: Visual Studio 2015

configuration:
  - Release
  - Debug

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: "0.1.0.{build}"
  assembly_file_version: "0.1.0.{build}"
  assembly_informational_version: "{version} ({branch})"

init:
  - git config --global core.autocrlf true

before_build:
  - cmd: nuget restore Superfaktura.sln

build:
  project: Superfaktura.sln
  verbosity: normal

test: off

cache:
  - packages -> **\packages.config
