#
# Superfaktura project AppVeyor build configuration
#

version: '0.1.0.{build}'

branches:
  only:
    - master
    - release
    - dev
    - /^(.*\/)?ci-.*$/

os: Visual Studio 2015

configuration:
  - Release
  - Debug

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: "0.1.0.{build}"
  assembly_file_version: "0.1.0.{build}"
  assembly_informational_version: "{version} ({branch})"

environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  CLI_VERSION: 1.0.0-preview2-003121

init:
  - git config --global core.autocrlf true
  - ps: $env:LABEL = "ci" + $env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
  - ps: Update-AppveyorBuild -Version "0.1.0-${env:LABEL}"

install:
  - ps: $url = "https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/$($env:CLI_VERSION)/dotnet-dev-win-x64.$($env:CLI_VERSION.ToLower()).zip"
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"
  - ps: mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null
  - ps: $tempFile = [System.IO.Path]::GetTempFileName()
  - ps: (New-Object System.Net.WebClient).DownloadFile($url, $tempFile)
  - ps: Add-Type -AssemblyName System.IO.Compression.FileSystem; [System.IO.Compression.ZipFile]::ExtractToDirectory($tempFile, $env:DOTNET_INSTALL_DIR)
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"

before_build:
  - ps: dotnet --info
  - ps: appveyor-retry dotnet restore -v Minimal

build_script:
  - dotnet build "src\Superfaktura" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%

after_build:
  - dotnet pack "src\Superfaktura" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts

test_script:
  - dotnet test "test\Superfaktura.Tests" -c %CONFIGURATION%

artifacts:
  - path: artifacts\**\*.*

cache:
  - '%USERPROFILE%\.nuget\packages -> **\project.json'
  - .dotnetsdk -> appveyor.yml
